version: '3.8'
services:
  client1:
    hostname: client1
    build:
      context: ./Client
      dockerfile: Dockerfile
    networks:
      - my-network
    environment:
      - CA_PATH=/app/rootCA.cer
      - BROKER_IP = ${MY_IP_ADDRESS}
      - USERNAME=client1
      - CLIENT_ID=alarm1
      - PASSWORD=password1
      - client1_MockedSmokeSensorState=RANDOM
     # - ASPNETCORE_Kestrel__Certificates__Default__Path="/app/rootCA.cer"
     # - ASPNETCORE_Kestrel__Certificates__Default__Password=""
  client2:
    hostname: client2
    build:
     context: ./Client
     dockerfile: Dockerfile
    networks:
      - my-network
    
    environment:
      - CA_PATH=/app/rootCA.cer
      - USERNAME=client2
      - CLIENT_ID=alarm2
      - PASSWORD=password2
      - client2_MockedSmokeSensorState=FALSE
     # - ASPNETCORE_Kestrel__Certificates__Default__Path="/app/rootCA.cer"
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=""
networks:
  my-network:
